# Generated by Django 3.2.23 on 2025-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphyApp', '0005_courseenrollment_is_paid_video_is_free_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('مقدماتی و متوسط', 'مقدماتی و متوسط'), ('خوش', 'خوش'), ('عالی و ممتاز', 'عالی و ممتاز'), ('فوق ممتاز', 'فوق ممتاز')], max_length=20, null=True, verbose_name='سطح'),
        ),
    ]
