# Generated by Django 3.2.23 on 2025-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphyApp', '0006_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('مقدماتی و متوسط', 'مقدماتی و متوسط'), ('خوش', 'خوش'), ('عالی و ممتاز', 'عالی و ممتاز'), ('فوق ممتاز', 'فوق ممتاز')], default='مقدماتی و متوسط', max_length=20, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='09123456789', max_length=15, verbose_name='شماره تلفن'),
        ),
    ]
